### ISSUE TITLE
[ERROR] Error running project created with Poi 8.0.0 generated via egoist/template-vue

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [egoist/poi#173]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

On windows 10, Node 7.9, current Poi version: 8.0.0 while using egoist/template-vue
```

C:\learn\sao\demo (master)
λ yarn dev
yarn dev v0.24.4
$ poi
> Running in development mode

Failed to parse "C:\learn\sao\demo\poi.config.js" as JSON, JS, or YAML.

 FAIL  Failed to start!

error Command failed with exit code 1.

C:\learn\sao\demo (master)

```

**Comment by egoist** [comment]
Fixed in `template-vue@2.4.1`

**Comment by CharlesOkwuagwu** [comment]
Thanks! ... Please how can we update project in place?
`npm update` does not seem to pick up the new template-vue
also, `ncu -n` also does not pick the update...

**Comment by egoist** [comment]
If you're using directly installed `template-vue`, just reinstall it to update, eg: `npm i -g template-vue`

If you're using `create-vue-app`, reinstall this instead.

**Comment by CharlesOkwuagwu** [comment]
This is what i did initially:

```
# Install sao first
yarn global add sao

# Generate project from git repo
sao egoist/template-vue demo
```
...
after your update to 2.4.1 i now did this:

`npm i -g template-vue`

I still get:

```
C:\learn\sao\demo (master)
λ yarn dev
yarn dev v0.24.4
$ poi
> Running in development mode

Failed to parse "C:\learn\sao\demo\poi.config.js" as JSON, JS, or YAML.

 FAIL  Failed to start!

error Command failed with exit code 1.
```
